name: Build and Start Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Start server
        run: yarn vite preview
